In [2]:
import glob
import pandas as pd
import numpy as np
import json

In [11]:
states = pd.read_csv('states.csv')
# for Code 1995
states = states.set_index(states["name"].apply(lambda x: x.replace(" ", "")
                                               .upper()))
# table = pd.DataFrame(index = list(states['id']) , columns = list(states['id']))
# table = table.fillna(0)

In [ ]:
i = 1990

In [24]:
states

,Code,id,name,lati,long
name,,,,,
Alaska,AK,2,Alaska,61.439418,-152.630008
Alabama,AL,1,Alabama,32.860979,-86.843844
Arkansas,AR,5,Arkansas,35.112916,-92.390076
America Samoa,AS,60,America Samoa,-7.209975,-170.771600
Arizona,AZ,4,Arizona,33.538652,-111.667784
California,CA,6,California,36.120548,-119.732413
Colorado,CO,8,Colorado,39.252753,-105.289699
Connecticut,CT,9,Connecticut,41.563671,-72.803370
District of Columbia,DC,11,District of Columbia,38.895380,-77.019529
Delaware,DE,10,Delaware,39.286356,-75.527876
Florida,FL,12,Florida,28.156184,-82.028187
Federated States of Micronesia,FM,64,Federated States of Micronesia,7.138297,151.503116
Georgia,GA,13,Georgia,33.046951,-83.691853
Guam,GU,66,Guam,13.444257,144.786297
Iowa,IA,19,Iowa,42.024919,-93.342777
Idaho,ID,16,Idaho,44.525179,-114.835818
Illinois,IL,17,Illinois,40.412743,-88.990033
Indiana,IN,18,Indiana,39.934865,-86.284023
Kansas,KS,20,Kansas,38.514917,-97.131739
Kentucky,KY,21,Kentucky,37.613671,-84.817170
Louisiana,LA,22,Louisiana,30.924395,-91.730588
Massachusetts,MA,25,Massachusetts,42.235964,-71.492968
Maryland,MD,24,Maryland,39.053017,-76.771289
Maine,ME,23,Maine,44.617454,-69.448121
Marshall Islands,MH,68,Marshall Islands,11.140496,166.410291
Michigan,MI,26,Michigan,43.447710,-84.742030
Minnesota,MN,27,Minnesota,45.547548,-94.126194
Missouri,MO,29,Missouri,38.384394,-92.467414
Northern Mariana Islands,MP,69,Northern Mariana Islands,15.190135,145.740804
Mississippi,MS,28,Mississippi,32.836151,-89.702898
Montana,MT,30,Montana,46.949118,-110.293906
North Carolina,NC,37,North Carolina,35.574668,-79.533199
North Dakota,ND,38,North Dakota,47.505710,-99.603593
Nebraska,NE,31,Nebraska,41.200929,-98.193695
New Hampshire,NH,33,New Hampshire,43.390640,-71.574491
New Jersey,NJ,34,New Jersey,40.387986,-74.519027
New Mexico,NM,35,New Mexico,34.706502,-106.137943
Nevada,NV,32,Nevada,38.016951,-116.708873
New York,NY,36,New York,42.192065,-75.121409
Ohio,OH,39,Ohio,40.390283,-82.737002
Oklahoma,OK,40,Oklahoma,35.513429,-97.000951
Oregon,OR,41,Oregon,44.518113,-122.050019
Pennsylvania,PA,42,Pennsylvania,40.629727,-77.559344
Puerto Rico,PR,72,Puerto Rico,18.290924,-66.320511
Palau,PW,70,Palau,7.225664,134.362169
Rhode Island,RI,44,Rhode Island,41.699338,-71.509798
South Carolina,SC,45,South Carolina,33.969880,-81.055365
South Dakota,SD,46,South Dakota,44.289445,-99.161860
Tennessee,TN,47,Tennessee,35.802394,-86.468996
Texas,TX,48,Texas,31.282067,-98.073658
Utah,UT,49,Utah,39.908453,-111.811009
Virginia,VA,51,Virginia,37.716236,-78.235407
Virgin Islands of the United States,VI,78,Virgin Islands of the United States,17.992228,-64.807018
Vermont,VT,50,Vermont,44.029486,-72.654350
Washington,WA,53,Washington,47.323329,-121.112621
Wisconsin,WI,55,Wisconsin,44.102919,-89.524178
West Virginia,WV,54,West Virginia,38.465505,-80.985950
Wyoming,WY,56,Wyoming,42.881633,-107.257498
Foreign,FR,57,Foreign,33.000000,-130.000000

In [16]:
# i= 1995
table = pd.DataFrame(index = list(states['id']) , columns = list(states['id']))
table.index.name = "State"
table = table.fillna(0)
filepaths = glob.glob('db/'+ str(i) + '*/*/*.xls')
for path in filepaths:    
#     year = path[path.find("/")+1:path.find("/")+5]
    # out is -1/ in is 1
    IO = (-1, 1)[path[path.find(".xls")-2]=="i"]
    State = path[path.rfind("/")+5:path.rfind("/")+7]
    State = State.replace(" ", "").upper()
#     print State
    try:
        tStateId = states.loc[State]["id"]
#              print tStateId
    except:
        continue
        
    df = pd.read_excel(path)
#     print df
    data = (df.ix[:, 0:4])
    data.columns = ["stateId", "stateShort", "stateName", "Number"]
    data = data[data.Number.notnull()]
    data = data[data.stateName.notnull()]
    data = data[3:]

    print data
    for s in data.iterrows():
        #print table.loc[1][1]

        if s[1]["stateId"] == "96":
            continue
        if(int(s[1][0]) == int(s[1][0])):
            if int(tStateId) == 1:
                print s[1][3]
            table.loc[tStateId][tStateId] = int(s[1][3])
            continue

        # fill in table
        try:
            table.loc[tStateId][int(s[1][0])] += int(s[1][3])*IO
        except:
            pass
#     break
for index, row in table.iterrows():
    for col, j in row.iteritems():
        if index != col:
            if table.loc[index][col] != -table.loc[col][index]:
                print str(col) + "and" + str(index) + "year" + str(i) + "failure"
table.to_csv("table" + str(i) + ".csv")

   stateId stateShort             stateName  Number
10      02         AK       AK Non-Migrants  190928
11      53         WA            WASHINGTON    1821
12      06         CA            CALIFORNIA    1607
13      48         TX                 TEXAS     907
14      41         OR                OREGON     770
15      57         FR       Foreign - Total     628
16      08         CO              COLORADO     575
17      12         FL               FLORIDA     534
18      37         NC        NORTH CAROLINA     463
19      04         AZ               ARIZONA     432
20      13         GA               GEORGIA     415
21      51         VA              VIRGINIA     343
22      30         MT               MONTANA     331
23      36         NY              NEW YORK     328
24      16         ID                 IDAHO     305
25      27         MN             MINNESOTA     264
26      26         MI              MICHIGAN     262
27      35         NM            NEW MEXICO     253
28      17         IL              ILLINOIS     229
29      49         UT                  UTAH     225
30      32         NV                NEVADA     224
31      42         PA          PENNSYLVANIA     221
32      21         KY              KENTUCKY     216
33      39         OH                  OHIO     211
34      40         OK              OKLAHOMA     203
35      15         HI                HAWAII     202
36      22         LA             LOUISIANA     200
37      29         MO              MISSOURI     194
38      20         KS                KANSAS     180
39      47         TN             TENNESSEE     170
40      55         WI             WISCONSIN     170
41      01         AL               ALABAMA     165
42      24         MD              MARYLAND     139
43      34         NJ            NEW JERSEY     139
44      25         MA         MASSACHUSETTS     138
45      45         SC        SOUTH CAROLINA     138
46      56         WY               WYOMING     124
47      38         ND          NORTH DAKOTA     104
48      05         AR              ARKANSAS     101
49      28         MS           MISSISSIPPI     101
50      18         IN               INDIANA     100
51      23         ME                 MAINE      96
52      19         IA                  IOWA      81
53      46         SD          SOUTH DAKOTA      77
54      09         CT           CONNECTICUT      67
55      31         NE              NEBRASKA      64
56      33         NH         NEW HAMPSHIRE      50
57      50         VT               VERMONT      42
58      54         WV         WEST VIRGINIA      37
59      10         DE              DELAWARE      24
60      44         RI          RHODE ISLAND      23
61      11         DC  DISTRICT OF COLUMBIA      18
   stateId stateShort             stateName   Number
10      01         AL       AL Non-Migrants  1424386
11      13         GA               GEORGIA     6771
12      12         FL               FLORIDA     6116
13      47         TN             TENNESSEE     3117
14      48         TX                 TEXAS     2777
15      28         MS           MISSISSIPPI     2614
16      57         FR       Foreign - Total     1925
17      06         CA            CALIFORNIA     1853
18      22         LA             LOUISIANA     1526
19      37         NC        NORTH CAROLINA     1489
20      51         VA              VIRGINIA     1360
21      17         IL              ILLINOIS     1207
22      39         OH                  OHIO     1114
23      36         NY              NEW YORK     1112
24      26         MI              MICHIGAN      913
25      45         SC        SOUTH CAROLINA      911
26      21         KY              KENTUCKY      739
27      18         IN               INDIANA      736
28      42         PA          PENNSYLVANIA      566
29      08         CO              COLORADO      559
30      29         MO              MISSOURI      498
31      24         MD              MARYLAND      472
32      05         AR              ARKANSAS      457
33      40         OK              OKLAHOMA      436
34      34         NJ            NEW JERSEY      399
35      53         WA            WASHINGTON      396
36      04         AZ               ARIZONA      384
37      20         KS                KANSAS      360
38      25         MA         MASSACHUSETTS      287
39      55         WI             WISCONSIN      283
40      15         HI                HAWAII      271
41      54         WV         WEST VIRGINIA      228
42      09         CT           CONNECTICUT      220
43      35         NM            NEW MEXICO      203
44      32         NV                NEVADA      167
45      02         AK                ALASKA      165
46      19         IA                  IOWA      164
47      27         MN             MINNESOTA      153
48      41         OR                OREGON      129
49      49         UT                  UTAH      120
50      31         NE              NEBRASKA      117
51      10         DE              DELAWARE       75
52      23         ME                 MAINE       74
53      33         NH         NEW HAMPSHIRE       72
54      30         MT               MONTANA       67
55      11         DC  DISTRICT OF COLUMBIA       65
56      56         WY               WYOMING       62
57      16         ID                 IDAHO       58
58      38         ND          NORTH DAKOTA       53
59      46         SD          SOUTH DAKOTA       53
60      44         RI          RHODE ISLAND       47
61      50         VT               VERMONT       27
1424386
   stateId stateShort             stateName  Number
10      05         AR       AR Non-Migrants  815762
11      48         TX                 TEXAS    5642
12      06         CA            CALIFORNIA    2912
13      40         OK              OKLAHOMA    2823
14      29         MO              MISSOURI    2573
15      47         TN             TENNESSEE    1752
16      22         LA             LOUISIANA    1534
17      17         IL              ILLINOIS    1523
18      12         FL               FLORIDA    1283
19      57         FR       Foreign - Total    1053
20      28         MS           MISSISSIPPI    1045
21      20         KS                KANSAS     854
22      13         GA               GEORGIA     589
23      37         NC        NORTH CAROLINA     579
24      26         MI              MICHIGAN     566
25      08         CO              COLORADO     539
26      04         AZ               ARIZONA     519
27      51         VA              VIRGINIA     505
28      18         IN               INDIANA     489
29      55         WI             WISCONSIN     453
30      19         IA                  IOWA     430
31      39         OH                  OHIO     398
32      01         AL               ALABAMA     396
33      53         WA            WASHINGTON     364
34      36         NY              NEW YORK     340
35      21         KY              KENTUCKY     315
36      42         PA          PENNSYLVANIA     278
37      31         NE              NEBRASKA     276
38      35         NM            NEW MEXICO     272
39      27         MN             MINNESOTA     256
40      45         SC        SOUTH CAROLINA     238
41      32         NV                NEVADA     231
42      02         AK                ALASKA     170
43      41         OR                OREGON     170
44      34         NJ            NEW JERSEY     169
45      24         MD              MARYLAND     157
46      15         HI                HAWAII     105
47      49         UT                  UTAH     103
48      25         MA         MASSACHUSETTS      92
49      16         ID                 IDAHO      89
50      30         MT               MONTANA      85
51      09         CT           CONNECTICUT      78
52      54         WV         WEST VIRGINIA      78
53      46         SD          SOUTH DAKOTA      75
54      56         WY               WYOMING      70
55      38         ND          NORTH DAKOTA      60
56      23         ME                 MAINE      41
57      10         DE              DELAWARE      38
58      33         NH         NEW HAMPSHIRE      38
59      11         DC  DISTRICT OF COLUMBIA      34
60      44         RI          RHODE ISLAND      20
61      50         VT               VERMONT      19
   stateId stateShort             stateName   Number
10      04         AZ       AZ Non-Migrants  1369200
11      06         CA            CALIFORNIA    21709
12      48         TX                 TEXAS     5481
13      17         IL              ILLINOIS     4918
14      08         CO              COLORADO     4041
15      35         NM            NEW MEXICO     3982
16      36         NY              NEW YORK     3639
17      57         FR       Foreign - Total     3375
18      53         WA            WASHINGTON     3297
19      12         FL               FLORIDA     2787
20      32         NV                NEVADA     2624
21      26         MI              MICHIGAN     2564
22      39         OH                  OHIO     2450
23      42         PA          PENNSYLVANIA     2125
24      49         UT                  UTAH     2034
25      41         OR                OREGON     1966
26      27         MN             MINNESOTA     1927
27      55         WI             WISCONSIN     1657
28      34         NJ            NEW JERSEY     1614
29      18         IN               INDIANA     1576
30      29         MO              MISSOURI     1437
31      51         VA              VIRGINIA     1335
32      25         MA         MASSACHUSETTS     1251
33      37         NC        NORTH CAROLINA     1191
34      19         IA                  IOWA     1189
35      20         KS                KANSAS     1135
36      13         GA               GEORGIA     1048
37      40         OK              OKLAHOMA      961
38      09         CT           CONNECTICUT      954
39      31         NE              NEBRASKA      895
40      24         MD              MARYLAND      884
41      16         ID                 IDAHO      818
42      15         HI                HAWAII      787
43      47         TN             TENNESSEE      720
44      30         MT               MONTANA      654
45      02         AK                ALASKA      632
46      56         WY               WYOMING      532
47      22         LA             LOUISIANA      515
48      21         KY              KENTUCKY      470
49      05         AR              ARKANSAS      462
50      46         SD          SOUTH DAKOTA      450
51      45         SC        SOUTH CAROLINA      441
52      01         AL               ALABAMA      410
53      33         NH         NEW HAMPSHIRE      387
54      38         ND          NORTH DAKOTA      359
55      23         ME                 MAINE      305
56      28         MS           MISSISSIPPI      276
57      50         VT               VERMONT      220
58      44         RI          RHODE ISLAND      176
59      54         WV         WEST VIRGINIA      138
60      10         DE              DELAWARE      129
61      11         DC  DISTRICT OF COLUMBIA      122
   stateId stateShort             stateName    Number
10      06         CA       CA Non-Migrants  10025767
11      57         FR       Foreign - Total     21220
12      48         TX                 TEXAS     15080
13      04         AZ               ARIZONA     11867
14      36         NY              NEW YORK     11328
15      53         WA            WASHINGTON     11260
16      12         FL               FLORIDA      8908
17      32         NV                NEVADA      8697
18      17         IL              ILLINOIS      8373
19      41         OR                OREGON      7510
20      08         CO              COLORADO      7416
21      51         VA              VIRGINIA      5826
22      25         MA         MASSACHUSETTS      5553
23      15         HI                HAWAII      5159
24      42         PA          PENNSYLVANIA      4691
25      34         NJ            NEW JERSEY      4613
26      39         OH                  OHIO      4492
27      26         MI              MICHIGAN      4315
28      13         GA               GEORGIA      3870
29      37         NC        NORTH CAROLINA      3619
30      24         MD              MARYLAND      3531
31      49         UT                  UTAH      3399
32      29         MO              MISSOURI      2982
33      27         MN             MINNESOTA      2862
34      35         NM            NEW MEXICO      2819
35      18         IN               INDIANA      2402
36      09         CT           CONNECTICUT      2323
37      40         OK              OKLAHOMA      2253
38      55         WI             WISCONSIN      2157
39      47         TN             TENNESSEE      2125
40      22         LA             LOUISIANA      2050
41      16         ID                 IDAHO      1845
42      20         KS                KANSAS      1821
43      19         IA                  IOWA      1501
44      02         AK                ALASKA      1354
45      45         SC        SOUTH CAROLINA      1353
46      01         AL               ALABAMA      1343
47      11         DC  DISTRICT OF COLUMBIA      1221
48      05         AR              ARKANSAS      1218
49      31         NE              NEBRASKA      1149
50      21         KY              KENTUCKY      1136
51      30         MT               MONTANA      1120
52      28         MS           MISSISSIPPI      1058
53      33         NH         NEW HAMPSHIRE       824
54      44         RI          RHODE ISLAND       621
55      56         WY               WYOMING       613
56      23         ME                 MAINE       603
57      46         SD          SOUTH DAKOTA       462
58      50         VT               VERMONT       376
59      38         ND          NORTH DAKOTA       361
60      10         DE              DELAWARE       327
61      54         WV         WEST VIRGINIA       311
   stateId stateShort             stateName   Number
10      08         CO       CO Non-Migrants  1328763
11      06         CA            CALIFORNIA    12978
12      48         TX                 TEXAS     8495
13      04         AZ               ARIZONA     3779
14      12         FL               FLORIDA     3502
15      17         IL              ILLINOIS     3266
16      57         FR       Foreign - Total     3151
17      36         NY              NEW YORK     2788
18      35         NM            NEW MEXICO     2565
19      53         WA            WASHINGTON     2232
20      20         KS                KANSAS     2183
21      51         VA              VIRGINIA     1890
22      31         NE              NEBRASKA     1796
23      27         MN             MINNESOTA     1775
24      39         OH                  OHIO     1738
25      26         MI              MICHIGAN     1713
26      42         PA          PENNSYLVANIA     1688
27      29         MO              MISSOURI     1667
28      56         WY               WYOMING     1606
29      49         UT                  UTAH     1417
30      55         WI             WISCONSIN     1362
31      25         MA         MASSACHUSETTS     1360
32      13         GA               GEORGIA     1359
33      32         NV                NEVADA     1314
34      40         OK              OKLAHOMA     1296
35      34         NJ            NEW JERSEY     1277
36      37         NC        NORTH CAROLINA     1199
37      19         IA                  IOWA     1192
38      24         MD              MARYLAND     1183
39      18         IN               INDIANA     1124
40      41         OR                OREGON     1123
41      30         MT               MONTANA      814
42      47         TN             TENNESSEE      808
43      22         LA             LOUISIANA      762
44      09         CT           CONNECTICUT      760
45      15         HI                HAWAII      726
46      01         AL               ALABAMA      608
47      16         ID                 IDAHO      608
48      46         SD          SOUTH DAKOTA      575
49      02         AK                ALASKA      553
50      45         SC        SOUTH CAROLINA      508
51      21         KY              KENTUCKY      470
52      05         AR              ARKANSAS      454
53      38         ND          NORTH DAKOTA      453
54      33         NH         NEW HAMPSHIRE      413
55      28         MS           MISSISSIPPI      335
56      23         ME                 MAINE      331
57      50         VT               VERMONT      273
58      11         DC  DISTRICT OF COLUMBIA      198
59      54         WV         WEST VIRGINIA      152
60      44         RI          RHODE ISLAND      150
61      10         DE              DELAWARE      111
   stateId stateShort             stateName   Number
10      09         CT       CT Non-Migrants  1214701
11      36         NY              NEW YORK     8389
12      25         MA         MASSACHUSETTS     3750
13      12         FL               FLORIDA     2574
14      06         CA            CALIFORNIA     1880
15      34         NJ            NEW JERSEY     1785
16      57         FR       Foreign - Total     1760
17      42         PA          PENNSYLVANIA     1272
18      44         RI          RHODE ISLAND     1021
19      51         VA              VIRGINIA     1008
20      48         TX                 TEXAS      871
21      37         NC        NORTH CAROLINA      694
22      17         IL              ILLINOIS      674
23      13         GA               GEORGIA      611
24      33         NH         NEW HAMPSHIRE      575
25      39         OH                  OHIO      571
26      24         MD              MARYLAND      559
27      23         ME                 MAINE      487
28      45         SC        SOUTH CAROLINA      441
29      08         CO              COLORADO      439
30      26         MI              MICHIGAN      398
31      53         WA            WASHINGTON      336
32      50         VT               VERMONT      320
33      04         AZ               ARIZONA      301
34      18         IN               INDIANA      225
35      47         TN             TENNESSEE      220
36      29         MO              MISSOURI      199
37      27         MN             MINNESOTA      195
38      11         DC  DISTRICT OF COLUMBIA      185
39      55         WI             WISCONSIN      179
40      15         HI                HAWAII      154
41      01         AL               ALABAMA      149
42      22         LA             LOUISIANA      149
43      41         OR                OREGON      132
44      20         KS                KANSAS      120
45      21         KY              KENTUCKY      120
46      10         DE              DELAWARE      110
47      32         NV                NEVADA      109
48      40         OK              OKLAHOMA       97
49      35         NM            NEW MEXICO       94
50      19         IA                  IOWA       86
51      49         UT                  UTAH       83
52      28         MS           MISSISSIPPI       70
53      54         WV         WEST VIRGINIA       64
54      31         NE              NEBRASKA       63
55      30         MT               MONTANA       55
56      16         ID                 IDAHO       53
57      02         AK                ALASKA       46
58      05         AR              ARKANSAS       44
59      56         WY               WYOMING       25
60      46         SD          SOUTH DAKOTA       22
61      38         ND          NORTH DAKOTA       16
   stateId stateShort        stateName  Number
10      11         DC  DC Non-Migrants  198860
11      24         MD         MARYLAND    5998
12      51         VA         VIRGINIA    3329
13      57         FR  Foreign - Total    2413
14      36         NY         NEW YORK    1200
15      06         CA       CALIFORNIA     965
16      42         PA     PENNSYLVANIA     641

In [15]:
for i in range(1990,1993):
    table = pd.DataFrame(index = list(states['id']) , columns = list(states['id']))
    table.index.name = "State"
    table = table.fillna(0)
    filepaths = glob.glob('db/'+ str(i) + '*/*/*.xls')
    for path in filepaths:    
        year = path[path.find("/")+1:path.find("/")+5]
        # out is -1/ in is 1
        IO = (-1, 1)[path[path.find(".xls")-1]=="n"]
        State = path[path.rfind("/")+1:(path.rfind(".xls")-5,path.rfind(".xls")-4)[IO==1]]
        State = State.replace(" ", "").upper()
        try:
            tStateId = states.loc[State]["id"]
#             print tStateId
        except:
            continue
        df = pd.read_excel(path)
        data = (df.ix[:, 0:4])
        data.columns = ["stateId", "stateShort", "stateName", "Number"]
        data = data[data.Number.notnull()]
        data = data[data.stateName.notnull()]

    #     print data
        for s in data.iterrows():
            #print table.loc[1][1]

            if s[1]["stateId"] == "96":
                continue
            if(int(s[1][0]) == int(tStateId)):
                if int(tStateId) == 1:
                    print s[1][3]
                table.loc[tStateId][tStateId] = int(s[1][3])
                continue

            # fill in table
            try:

                table.loc[tStateId][int(s[1][0])] += int(s[1][3])*IO
            except:
                pass
    for index, row in table.iterrows():
        for col, j in row.iteritems():
            if index != col:
                if table.loc[index][col] != -table.loc[col][index]:
                    print str(col) + "and" + str(index) + "year" + str(i) + "failure"
    table.to_csv("table" + str(i) + ".csv")

1334900
1334900
1360625
1360625
1374133
1374133
57and2year1992failure
57and1year1992failure
57and5year1992failure
57and4year1992failure
57and6year1992failure
57and8year1992failure
57and9year1992failure
57and11year1992failure
57and10year1992failure
57and12year1992failure
57and13year1992failure
57and19year1992failure
57and16year1992failure
57and17year1992failure
57and18year1992failure
57and20year1992failure
57and21year1992failure
57and22year1992failure
57and25year1992failure
57and24year1992failure
57and23year1992failure
57and26year1992failure
57and27year1992failure
57and29year1992failure
57and28year1992failure
57and30year1992failure
57and37year1992failure
57and38year1992failure
57and31year1992failure
57and33year1992failure
57and34year1992failure
57and35year1992failure
57and32year1992failure
57and36year1992failure
57and39year1992failure
57and40year1992failure
57and41year1992failure
57and42year1992failure
57and44year1992failure
57and45year1992failure
57and46year1992failure
57and47year1992failure
57and48year1992failure
57and49year1992failure
57and51year1992failure
57and50year1992failure
57and53year1992failure
57and55year1992failure
57and54year1992failure
57and56year1992failure
2and57year1992failure
1and57year1992failure
5and57year1992failure
4and57year1992failure
6and57year1992failure
8and57year1992failure
9and57year1992failure
11and57year1992failure
10and57year1992failure
12and57year1992failure
13and57year1992failure
19and57year1992failure
16and57year1992failure
17and57year1992failure
18and57year1992failure
20and57year1992failure
21and57year1992failure
22and57year1992failure
25and57year1992failure
24and57year1992failure
23and57year1992failure
26and57year1992failure
27and57year1992failure
29and57year1992failure
28and57year1992failure
30and57year1992failure
37and57year1992failure
38and57year1992failure
31and57year1992failure
33and57year1992failure
34and57year1992failure
35and57year1992failure
32and57year1992failure
36and57year1992failure
39and57year1992failure
40and57year1992failure
41and57year1992failure
42and57year1992failure
44and57year1992failure
45and57year1992failure
46and57year1992failure
47and57year1992failure
48and57year1992failure
49and57year1992failure
51and57year1992failure
50and57year1992failure
53and57year1992failure
55and57year1992failure
54and57year1992failure
56and57year1992failure

In [17]:
table

,2,1,5,60,4,6,8,9,11,10,...,47,48,49,51,50,53,55,54,56,57
State,,,,,,,,,,,,,,,,,,,,,
2,190928,0,-69,0,-200,253,22,21,-4,8,...,-75,-176,-38,-33,16,-517,-30,-8,30,153
1,0,1424386,61,0,-26,510,-49,71,7,18,...,-590,-93,-28,34,-1,-42,86,99,10,262
5,69,-61,815762,0,57,1694,85,34,4,11,...,-362,686,-3,62,-2,38,193,25,18,532
60,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,200,26,-57,0,1369200,9842,262,653,23,73,...,-66,549,328,301,111,609,762,3,148,1430
6,-253,-510,-1694,0,-9842,10025767,-5562,443,256,-8,...,-1389,-6697,-2721,-1297,-31,-7666,-402,-135,-325,7141
8,-22,49,-85,0,-262,5562,1328763,321,52,45,...,-104,1919,-33,491,95,-209,390,15,86,772
9,-21,-71,-34,0,-653,-443,-321,1214701,-96,-24,...,-174,-277,-50,-740,-290,-228,-41,-32,-16,372
11,4,-7,-4,0,-23,-256,-52,96,198860,10,...,3,-34,5,-1502,-1,-58,40,-14,2,1540
10,-8,-18,-11,0,-73,8,-45,24,-10,264779,...,-65,-50,-10,-89,-10,-42,15,0,-11,167
12,122,-515,-138,0,-693,2298,-562,3420,135,375,...,-1775,-1295,-47,2568,202,-237,823,153,25,3208
64,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,12,1589,112,0,-30,2475,107,955,84,118,...,80,834,42,1484,42,63,248,103,19,1411
66,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,13,-22,-166,0,-480,602,-214,6,12,6,...,-120,-240,-2,-46,-12,-42,-252,-2,-23,1151
16,66,3,-1,0,-34,2164,57,10,-4,17,...,-33,70,-146,43,20,546,17,-4,95,159
17,-9,-385,-640,0,-2877,228,-1262,245,11,21,...,-1161,-1752,-99,-63,-6,-360,-2748,-17,-19,2534
18,35,-210,-85,0,-660,976,-367,75,-22,6,...,-848,-150,5,134,-26,-65,-118,78,30,1452
20,-44,-25,-222,0,-343,703,-332,8,-32,-8,...,-274,-1000,2,-46,-11,-125,-2,-16,32,494
21,-60,-16,57,0,-42,478,66,66,7,11,...,-1040,-90,38,167,17,17,33,168,-10,541
22,8,-329,-280,0,-126,601,-177,20,0,-5,...,-588,-2176,-43,-68,-1,-169,12,14,-4,756
25,-37,-59,12,0,-643,-880,-424,1637,-69,-4,...,-169,-135,11,-211,-68,-279,67,11,16,2686
24,65,-50,-17,0,-391,23,-462,211,4869,-492,...,-409,-613,-56,-1905,-24,-204,-36,-826,-17,1697
23,-10,-8,-12,0,-123,52,-115,365,-10,9,...,-73,-39,-4,-35,23,-70,1,-6,-2,171
68,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,60,-224,-139,0,-1125,235,-440,132,-49,-9,...,-1074,108,-76,121,-3,-134,-445,3,-15,2138
27,18,20,-45,0,-803,507,-379,61,-5,25,...,-84,66,-5,103,14,-132,274,21,19,1347
29,48,34,25,0,-266,1380,-51,78,-12,61,...,-211,-114,57,183,14,-26,187,38,23,953
69,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,-3,-199,-155,0,-43,270,-33,24,-13,10,...,186,-36,-43,58,6,-30,30,14,11,304
30,-41,-7,-31,0,-119,816,41,29,1,2,...,-5,35,-30,32,7,147,79,1,113,155
37,-29,211,-68,0,-110,2031,27,1225,187,105,...,-521,620,10,3603,167,70,219,750,9,1865
38,-5,-21,-26,0,-170,219,-101,10,1,1,...,-14,-109,0,-18,-4,-7,-82,5,21,259
31,46,24,-48,0,-360,815,-205,9,-16,-2,...,-86,-196,-9,2,2,-11,-1,-4,8,638
33,2,-7,-8,0,-164,-22,-136,403,1,6,...,-20,-75,-26,-74,138,-12,10,-2,-17,257
34,-50,-147,-68,0,-1070,-1056,-661,-183,-144,-614,...,-447,-898,-49,-1922,-190,-271,-102,-108,-37,850
35,13,-32,-76,0,-725,1257,-236,84,44,0,...,-86,134,11,69,15,-45,64,10,40,335
32,125,-41,-4,0,502,12253,110,107,4,-1,...,-18,397,167,181,27,58,193,2,185,340
36,-57,-495,-111,0,-2334,-2550,-1313,-2597,-8,-424,...,-1093,-2161,-198,-3804,-573,-722,-60,-143,-94,4211
39,10,-252,-21,0,-1005,318,-453,122,-75,67,...,-1119,-574,-35,-55,-13,-162,-125,523,-32,2919
40,74,-19,-183,0,18,1406,180,28,-5,28,...,-123,-1188,73,11,3,60,8,-9,88,817
41,319,5,16,0,-35,8008,284,102,20,22,...,11,427,242,226,32,-171,168,-2,69,815
42,-39,-103,-94,0,-1162,-489,-680,350,-129,-1164,...,-566,-749,-81,-1598,-83,-344,-175,-184,-54,2358
72,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
70,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,-3,-9,-15,0,-100,60,-58,109,-12,-12,...,-46,-86,-9,-138,-29,-26,3,-3,-1,284
45,19,11,13,0,-30,458,-21,334,53,59,...,-389,3,13,-456,51,-46,95,274,19,274
46,14,-27,-12,0,-155,208,-36,5,1,-7,...,-43,-106,-12,-14,5,28,-59,10,44,232
47,75,590,362,0,66,1389,104,174,-3,65,...,1865603,736,60,994,29,105,276,228,20,1207
48,176,93,-686,0,-549,6697,-1919,277,34,50,...,-736,6073166,19,719,55,-206,198,-3,67,5106
49,38,28,3,0,-328,2721,33,50,-5,10,...,-60,-19,585449,100,8,29,33,-11,178,598
51,33,-34,-62,0,-301,1297,-491,740,1502,89,...,-994,-719,-100,2347506,51,-299,-46,-60,-12,3658
50,-16,1,2,0,-111,31,-95,290,1,10,...,-29,-55,-8,-51,214861,-31,-1,-1,8,122
53,517,42,-38,0,-609,7666,209,228,58,42,...,-105,206,-29,299,31,1906008,94,6,27,2069
55,30,-86,-193,0,-762,402,-390,41,-40,-15,...,-276,-198,-33,46,1,-94,1903592,1,-35,883
54,8,-99,-25,0,-3,135,-15,32,14,0,...,-228,3,11,60,1,-6,-1,581837,-7,243
56,-30,-10,-18,0,-148,325,-86,16,-2,11,...,-20,-67,-178,12,-8,-27,35,7,165039,39
57,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
table.to_csv("test.csv")